# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    name: Python ${{ matrix.python-version }}

    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Install Python dependencies
        uses: py-actions/py-dependency-install@v2
            
      #- name: Setup python
      #  uses: actions/set-python@v2
      #  with: 
      #    python-version: ${{ matrix.python-version }}
      - run:  python mytest.py -in log.txt -max-path 30 -out out.json -max-client-ips 15 

      # Testing
      - name: Run python test
        run:  python -m pytest

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, Jin!
        
      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
